"""
Auto MPG Prediction API
-----------------------
Run locally:
    uvicorn app:app --reload

Docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field, field_validator

# ── Load the trained pipeline once at startup ─────────────────────────────────
model = joblib.load("model.pkl")

app = FastAPI(
    title="Auto MPG Predictor",
    description="Predict a car's fuel efficiency (miles per gallon) from its specs.",
    version="1.0.0",
)

# ── Input schema (Pydantic validates + documents the API automatically) ────────
class CarFeatures(BaseModel):
    cylinders:    int   = Field(..., ge=3, le=8,      example=4,     description="Number of cylinders")
    displacement: float = Field(..., gt=0,            example=140.0, description="Engine displacement (cubic inches)")
    horsepower:   float = Field(None,                 example=90.0,  description="Horsepower (leave null if unknown)")
    weight:       int   = Field(..., gt=0,            example=2264,  description="Vehicle weight (lbs)")
    acceleration: float = Field(..., gt=0,            example=15.5,  description="0-60 mph time (seconds)")
    model_year:   int   = Field(..., ge=70, le=82,    example=79,    description="Model year (70–82)")
    origin:       int   = Field(..., ge=1, le=3,      example=2,     description="1=USA, 2=Europe, 3=Japan")

    @field_validator("horsepower", mode="before")
    @classmethod
    def coerce_hp(cls, v):
        if v == "?" or v == "":
            return None
        return v

# ── Output schema ─────────────────────────────────────────────────────────────
class PredictionResponse(BaseModel):
    predicted_mpg:      float
    efficiency_label:   str
    model_version:      str = "ridge-v1.0"

def _efficiency_label(mpg: float) -> str:
    if mpg < 18:  return "Low efficiency 🔴"
    if mpg < 28:  return "Average efficiency 🟡"
    return             "High efficiency 🟢"

# ── Routes ────────────────────────────────────────────────────────────────────
@app.get("/", tags=["Health"])
def root():
    return {"status": "ok", "message": "Auto MPG API is running. Visit /docs for usage."}

@app.get("/health", tags=["Health"])
def health():
    return {"status": "healthy"}

@app.post("/predict", response_model=PredictionResponse, tags=["Prediction"])
def predict(car: CarFeatures):
    """
    Send car specs → receive predicted MPG.

    Example request body:
    ```json
    {
      "cylinders": 4,
      "displacement": 140.0,
      "horsepower": 90.0,
      "weight": 2264,
      "acceleration": 15.5,
      "model_year": 79,
      "origin": 2
    }
    ```
    """
    # Build a DataFrame with the exact column names the pipeline expects
    input_df = pd.DataFrame([{
        "cylinders":    car.cylinders,
        "displacement": car.displacement,
        "horsepower":   car.horsepower,   # None → pipeline imputes median
        "weight":       car.weight,
        "acceleration": car.acceleration,
        "model year":   car.model_year,   # match training column name
        "origin":       car.origin,
    }])

    try:
        prediction = float(model.predict(input_df)[0])
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")

    return PredictionResponse(
        predicted_mpg    = round(prediction, 2),
        efficiency_label = _efficiency_label(prediction),
    )
